all:
	make clean
	make invasion

clean:
	!Rm *.o

invasion:	invasion.o model.o input.o renderer.o rast.o events.o psg.o effects.o music.o
	cc68x -g invasion.o model.o input.o renderer.o rast.o events.o psg.o effects.o music.o -o invasion
    
invasion.o:	invasion.c invasion.h
	cc68x -g -c invasion.c

model.o:	model.c model.h
	cc68x -g -c model.c    
	
input.o:	input.c input.h
	cc68x -g -c input.c

renderer.o:	renderer.c render.h
	cc68x -g -c renderer.c
	
events.o:	events.c events.h
	cc68x -g -c events.c	

rast.o:	rast.c rast.h
	cc68x -g -c rast.c
	
psg.o:	psg.c psg.h
	cc68x -g -c psg.c
	
effects.o:	effects.c effects.h
	cc68x -g -c effects.c
	
music.o:	music.c music.h
	cc68x -g -c music.c
